"""Offline authoring tool. No runtime generation, machine data, or network access.

Small domain-specific vocabularies are edited here; the shipped JSON/header are
the audit surface. Stable IDs are hashes of fictional text, not installation IDs.
"""
from pathlib import Path
import random, hashlib, json, re

ROOT = Path(__file__).parent
RNG = random.Random(417031)
# family | singular objects | routine state fragments | irregular state fragments
# States deliberately describe their own domain rather than generic spooky verbs.
DOMAINS = r'''
access|west permit;loading pass;upper clearance;visitor slip;entry stamp;temporary pass;service permit;side access;renewal form;admission card;gate release;day pass|available;renewed;valid until closing;held at reception;awaiting countersignature;issued without surcharge;filed with admissions;limited to one entry;ready for collection;accepted at the side gate;retained for review;returned to the desk;restricted to working hours;approved in pencil;not transferable|valid on both sides;issued before application;accepted by an absent office;renewed after surrender;still active after cancellation;stamped with an extra entrance;returned without its holder;recognized by the closed gate;valid for a room not listed
doors|lower latch;service door;brass hinge;side bolt;inner handle;rear threshold;door closer;upper catch;weather seal;inspection hatch;outer plate;spare hinge|oiled;adjusted;left unlatched;secured for cleaning;awaiting a washer;aligned with the frame;checked for wear;replaced at noon;held open for delivery;painted on one side;free of obstruction;marked for removal;fitted with a new spring;tested without load;due for lubrication|warm on the unheated side;listed as an entrance only;closing against no resistance;returned with a second inside;turning without the handle;missing from the open position;bolted in the inventory photograph;opening onto the same threshold;fitted before the wall
rooms|west office;lower room;spare room;waiting area;cleaning room;rear annex;small chamber;upper alcove;service bay;quiet room;side room;vacant office|available for inspection;reserved until noon;cleared of furniture;awaiting repainting;assigned to storage;measured for shelving;locked for cleaning;ready for use;listed on the floor plan;ventilated;released to maintenance;fitted with a new blind;closed for inventory;awaiting a nameplate;unoccupied|occupied on paper;larger after closure;reserved by its former number;empty with the light on;included on neither floor;remaining after demolition;measured from an absent wall;occupied by the previous arrangement;still on the departure list
corridors|east passage;service corridor;lower landing;rear walkway;narrow passage;covered link;upper hallway;side passage;connecting hall;cross passage;west landing;staff route|clear;reopened;marked for cleaning;available to deliveries;lit throughout;closed at dusk;painted to the corner;checked for obstructions;included in the route sheet;measured for cable;fitted with a rail;awaiting new signs;open at both ends;reserved for transport;not a storage area|longer on the return route;absent between landings;ending at its own sign;used before opening;shorter without the lights;included twice in the route;still carrying foot traffic after closure;visible only from the far end;connecting the same floor to itself
schedules|morning rota;late shift;inspection slot;delivery window;break interval;cleaning round;weekly timetable;closure period;service appointment;afternoon session;spare interval;arrival schedule|approved;posted;revised in ink;held for confirmation;extended by one hour;filed under operations;cancelled by request;limited to weekdays;awaiting a replacement copy;assigned to reception;confirmed by telephone;available for amendment;noted on the board;returned unsigned;effective from monday|continuing after its end;missing an entire afternoon;already completed tomorrow;repeating the unused hour;approved by the preceding shift;dated between two days;including a break nobody took;arriving ahead of its notice;still in effect before issue
inspections|annual check;ladder inspection;seal check;routine survey;safety round;surface review;visual check;preliminary check;follow-up visit;opening inspection;fixture survey;final review|complete;postponed;booked for morning;limited to visible surfaces;awaiting written approval;passed with reservations;recorded on the reverse;due next quarter;performed without tools;assigned to the outside team;closed without repair;returned for clarification;filed as satisfactory;approved for repetition;subject to access|complete without a visit;passed by the removed fixture;showing wear not yet present;recorded from the other side;still under way in the empty room;approved with no result;finding the same missing item;dated before the object arrived;completed twice by one signature
inventory|shelf count;spare stock;returned lot;tool register;linen tally;parts list;storage count;loose stock;crate tally;reserve list;cabinet count;issued stock|balanced;entered in the ledger;checked against receipts;reduced by one;available on request;awaiting recount;held at stores;released in batches;separated by size;counted by hand;listed without value;marked as complete;returned to storage;reconciled at closing;subject to adjustment|correct until the shelf was emptied;including an unissued item;shorter than the empty list;balanced by a missing receipt;increasing during the recount;missing the item that was returned;listed under yesterday's total;counted without opening the cabinet;containing one more absence
deliveries|first consignment;sealed parcel;late delivery;small crate;returned carton;office shipment;replacement parcel;bulk delivery;packing slip;unclaimed box;morning load;last carton|received;unpacked;held at the depot;due after lunch;checked for damage;left with reception;awaiting a receipt;accepted without wrapping;returned to sender;stored upright;listed as fragile;released for collection;weighed on arrival;left at the side entrance;sealed with tape|signed for before dispatch;arriving without a sender;weighing less when full;containing its own receipt;returned before acceptance;already waiting in the locked bay;listed as both sent and lost;packed around an empty space;delivered to the former address
replacements|spare spring;new bracket;replacement plate;exchange unit;fresh seal;reserve handle;spare wheel;new panel;replacement pin;exchange fitting;spare cover;new insert|fitted;ordered;approved for use;awaiting collection;held for exchange;matched to the old part;returned unopened;tested on the bench;not required this month;stored with its label;available in one size;included in the service kit;awaiting installation;checked against the sample;supplied without screws|older than the removed part;already bearing the service mark;fitted in the wrong photograph;returned by the original;matching a part never ordered;worn only on the inside;supplied with yesterday's damage;listed as its own predecessor;still attached to the discarded unit
signatures|approval mark;second signature;receipt initial;blue initial;witness mark;counterstamp;final signature;acceptance mark;release initial;authorizing mark;register signature;margin initial|legible;required on both copies;entered in blue;awaiting verification;accepted without a date;placed below the line;returned for correction;filed with the original;not required for copies;missing from the reverse;recorded in the margin;checked at reception;valid for one issue;supplied on request;reserved for the witness|present beneath the blank space;matching the unsigned copy;appearing before the ink;withdrawn by another mark;assigned to a vacant post;legible only on the carbon sheet;older than the paper;approved by its own witness;present on the unprinted form
keys|brass key;cabinet key;spare key;gate key;small key;master blank;tagged key;service key;drawer key;reserve blank;returned key;long key|returned;tagged;available at reception;issued against a deposit;kept in the upper drawer;awaiting duplication;matched to the lock;filed under stores;not issued after dusk;checked for wear;attached to a plain ring;held for collection;cut from the sample;accepted without a tag;marked in green|returned twice;fitting a removed lock;warm before issue;missing its assigned door;listed as still in use after return;cut before the sample;carrying the wrong silence;opening the locked inventory box from within;received with no return entry
cabinets|lower cabinet;parts cupboard;wall locker;filing cabinet;glass cabinet;spare cupboard;linen cabinet;corner locker;tool cupboard;service cabinet;empty locker;side cupboard|unlocked;labelled;cleared for cleaning;assigned to spare parts;closed at the end of shift;fitted with a shelf;awaiting a latch;available to stores;kept dry;checked for corrosion;opened for inventory;secured without a seal;emptied at noon;reserved for records;not to be moved|deeper than its recess;empty on only one shelf;locked around the spare key;holding the removed wall;listed as open after removal;closing without a back panel;still occupied on the tally sheet;showing a second set of hinges;returning the empty box
lights|landing lamp;desk bulb;emergency lamp;rear light;wall fitting;inspection light;small lamp;service bulb;ceiling fitting;pilot light;spare bulb;door lamp|replaced;tested;left on for cleaning;switched off at noon;awaiting a cover;rated for continuous use;connected to the reserve circuit;listed for replacement;cleaned on the outside;held as a spare;checked without the shade;working at reduced output;aligned with the bracket;released for use;not included in the count|lit on the disconnected plan;cool while the spare is warm;illuminating its former bracket;still listed as off;casting the missing shade;flickering in the written report;on before the circuit closes;working only in the empty bay;reflected by the unlit bulb
shadows|shelf shadow;rail shadow;corner shade;window shadow;stair shadow;doorway shade;beam shadow;desk shadow;wall shade;overhang shadow;lamp shadow;cabinet shade|noted;included in the survey;marked on the sketch;visible at noon;outside the work area;left unmeasured;recorded without scale;excluded from inventory;checked against the lamp;within the marked boundary;listed as temporary;unchanged at inspection;not an obstruction;omitted from the tracing;reserved for comparison|present without the shelf;shifted before the light;remaining on the removed panel;deeper on the illuminated side;registered as an object;missing from its own outline;arriving after the room is empty;crossing the shut door;shorter in the dark
geometry|outer edge;lower plane;spare angle;cross section;corner profile;rear contour;surface outline;inner radius;upper face;reference shape;cut edge;side plane|measured;aligned;checked against the drawing;within tolerance;marked for revision;retained in the plan;filed without scale;approved as drawn;extended to the boundary;omitted from the copy;available as a tracing;returned to drafting;not load-bearing;verified at two points;subject to survey|larger than its enclosed area;folded through the measurement;present after deletion;matching the missing side;drawn from the inside out;returning to an unmarked point;crossing its own depth;occupying the gap in the diagram;listed without a surface
history|earlier revision;previous state;old entry;retained copy;first record;withdrawn version;former layout;last amendment;initial draft;prior arrangement;older tracing;superseded plan|retained;filed;available for reference;marked as obsolete;returned to archives;not for circulation;copied without annotations;held pending review;checked against the original;excluded from the new edition;stored flat;listed by revision;approved for disposal;kept with its envelope;withdrawn from use|newer than its replacement;showing the present omission;corrected by an unsigned future entry;missing its first page again;including an unopened room;returning after disposal;older only on the reverse;retained by a nonexistent department;already referring to the next version
frames|held frame;spare frame;reference image;last sample;output frame;comparison image;first sample;retained image;empty frame;test image;source frame;still image|available;retained for comparison;copied without labels;held for review;accepted at full size;listed as complete;discarded after inspection;stored with the test sheet;checked at the boundary;not for circulation;returned without annotation;recorded in sequence;released for output;kept as a reference;excluded from the average|arriving without its predecessor;matching an unrendered view;presenting the removed corner;older at the right edge;containing an extra stillness;counted by the wrong sequence;retained before capture;showing the absent lamp;appearing in two different histories
presentation|first output;second present;display copy;delivery interval;release window;front buffer;output queue;presentation slot;visible copy;delivery record;final output;display interval|accepted;released;held for delivery;checked at the boundary;recorded in order;available after review;not included in the tally;returned without a label;assigned to output;listed as delivered;reserved for testing;cleared at closing;limited to one copy;awaiting confirmation;included in the report|delivered before release;occupied by an unlisted copy;complete with no visible output;arriving between intervals;listed twice under one release;waiting after its own delivery;credited to the empty queue;visible in the previous slot;accepted by the wrong boundary
reconstruction|recovered outline;restored section;reference surface;revised contour;reassembled edge;replacement shape;retained detail;restored corner;partial model;recovered view;reference seam;revised surface|approved;checked;held for comparison;accepted without annotation;listed as provisional;returned for revision;complete at the boundary;available at reduced size;filed with the source;marked for review;not included in the original;aligned to the reference;released for inspection;omitted from the final copy;verified by tracing|matching a missing source;older than the reference;restored without removal;containing yesterday's outline;complete where the original was blank;already present in the spare copy;retaining a discarded angle;assembled around an absence;recovered from an empty history
maintenance|service note;repair order;bench test;work sheet;cleaning entry;spare allocation;service docket;inspection ticket;repair estimate;tool request;adjustment note;work permit|closed;approved;awaiting parts;returned to the workshop;limited to one fixture;filed as complete;charged to maintenance;held for a second opinion;available without appointment;issued in duplicate;scheduled for morning;checked against the work sheet;not to be extended;accepted without comment;marked for follow-up|closed by the unrepaired fixture;open after completion;issued by the retired bench;including a tool not supplied;completed before allocation;returned with no fault listed;approved for an absent installation;dated beneath the erasure;still accumulating work after closure
time|opening time;recorded minute;clock entry;closing hour;service date;printed interval;arrival time;reference date;departure minute;stored hour;calendar entry;appointment time|confirmed;amended;written in the margin;listed on the board;held for verification;recorded without seconds;rounded to the minute;approved for publication;copied from the schedule;returned for correction;included in the register;not guaranteed;available on request;checked by hand;filed under appointments|earlier on the duplicate;missing from the clock face;continuing past its deletion;listed between consecutive seconds;arriving without a date;correct only on the carbon copy;repeating after the bell stops;older than its calendar;replaced by a blank interval
records|missing page;duplicate sheet;unsigned form;blank register;retained docket;carbon copy;index card;loose entry;closed file;margin note;withdrawn sheet;last receipt|filed;indexed;available for copying;returned to the tray;marked as incomplete;held pending review;stored without a cover;checked against the register;listed by subject;approved for circulation;not for disposal;included in the amendment;copied on the reverse;issued without attachments;awaiting a signature|numbered before the first page;matching the missing original;signed in the blank column;containing a second omission;corrected without an earlier entry;older after copying;filed beneath its own index;returned by the closed archive;complete except for its contents
measurements|second reading;wall measurement;spare gauge;reference length;lower clearance;depth reading;bench scale;recorded width;ceiling height;edge reading;test weight;outside measure|checked;within tolerance;entered in pencil;rounded down;available for comparison;recorded without units;returned for confirmation;taken at both ends;held as a reference;approved for use;listed on the drawing;repeated at noon;excluded from the average;marked as provisional;subject to calibration|smaller from inside;unchanged after extension;taken before the surface existed;including the space behind the ruler;correct only when unread;shorter than the zero mark;repeating with no instrument;filed under the wrong dimension;larger after subtraction
staff|relief post;night desk;vacant position;duty roster;attendance slip;shift handover;staff notice;reception post;service desk;return slip;crew allocation;temporary post|assigned;posted;awaiting confirmation;covered until closing;listed as vacant;held for relief;included in the rota;returned to administration;available for transfer;closed at noon;recorded in attendance;reserved for training;not to be extended;approved without amendment;left unfilled|signed out before arrival;staffed on the empty rota;covered by the preceding absence;retained after abolition;listed under two departures;present only in the handover;assigned to a closed desk;vacant with completed attendance;relieved by its own return
weather|rain entry;wind reading;frost notice;cloud record;storm interval;dry period;weather sheet;damp report;clear interval;pressure reading;sunlight record;thaw notice|recorded;posted;included in the report;held for comparison;noted at the gate;checked against the gauge;available for review;filed without comment;listed as temporary;omitted from the summary;measured outside;returned for confirmation;accepted as observed;copied to the schedule;not an access restriction|recorded on the indoor sheet;continuing after the roof was removed;clear beneath the wet mark;colder inside the closed envelope;beginning before the clouds;listed at the wrong window;dry on the reverse;remaining after the forecast is withdrawn;arriving in the covered passage
power|reserve circuit;spare cell;isolation switch;voltage reading;power entry;fuse carrier;service feed;test socket;return line;auxiliary supply;breaker label;charge record|isolated;checked;available on request;switched off for service;held in reserve;tested without load;connected to the bench;listed at the panel;marked for inspection;returned to stores;approved at reduced load;not for temporary use;fitted with a cover;measured at the socket;disconnected|live on the disconnected side;charged before connection;feeding the removed outlet;still recorded as isolated;returning without a supply;measured in the empty holder;active only on the old diagram;drawing from the spare label;holding charge after replacement
storage|reserve shelf;upper rack;empty bay;rear bin;loose container;spare tray;sealed tote;dry store;packing shelf;returned bin;lower rack;archive box|cleared;labelled;kept dry;reserved for parts;available to stores;checked for damage;held until collection;listed as empty;assigned to returns;stacked upright;closed for inventory;not to be moved;included in the tally;cleaned at noon;awaiting a cover|full on the empty list;holding its former contents;deeper after unpacking;returned with a missing corner;occupied beneath the shelf;sealed before filling;keeping the removed label;empty only from above;listed as both issued and stored
stairs|lower flight;spare tread;upper step;service stair;landing rail;rear flight;stair nosing;middle step;side rail;bottom tread;upper landing;stair bracket|checked;repaired;open to service;marked for cleaning;awaiting a fixing;included in the survey;painted at the edge;cleared of storage;fitted with a strip;closed at dusk;available to deliveries;measured from below;listed on the plan;not for loading;approved for use|returning to the first landing;counted from an absent step;higher on the descent;including one unbuilt tread;still in use after removal;ending below the ground floor;listed between landings;creaking on the concrete plan;missing only from above
elevators|lift car;service cage;upper stop;call button;landing indicator;spare cable;car floor;return switch;lift register;lower stop;inspection lever;car panel|tested;checked;reserved for freight;held at the lower stop;available to service;listed as stationary;awaiting a cover;cleaned after use;not to be loaded;recorded in the log;isolated for inspection;returned to ground;fitted with a new plate;approved without passengers;due for service|arriving without a call;indicating a removed floor;empty with a completed load entry;returning before departure;held between identical stops;stopping at the unbuilt landing;recorded as descending at both ends;carrying its own inspection sheet;moving only on the indicator
windows|rear pane;upper sash;spare glass;small window;service casement;inside blind;window latch;lower pane;side glazing;outer sill;fixed light;window frame|cleaned;checked;left open for ventilation;closed at dusk;awaiting a seal;measured for replacement;included in the survey;fitted with plain glass;kept clear;not an exit;available for inspection;listed on the plan;painted on the outside;released for repair;marked with tape|showing the previous room;open only in reflection;looking onto an unlisted floor;retaining the removed view;clear on the covered side;closed behind the glass;listed as an interior wall;reflecting the spare pane first;lit from the erased side
space|unused corner;empty recess;clear gap;spare alcove;open section;vacant bay;unmarked area;lower void;free margin;unused portion;reserved gap;rear recess|available;measured;kept clear;reserved for expansion;excluded from storage;marked on the drawing;checked for access;left unassigned;listed as unused;included in the survey;not for filling;held pending review;available without approval;recorded without scale;left undisturbed|occupied by its measurement;larger when filled;missing from the empty plan;retained after the wall returns;assigned to two absences;holding the omitted object;reserved before clearance;full only in the register;counted as a fixture
sounds|relay click;pipe noise;floor creak;bell note;low hum;air hiss;motor tone;drain sound;loose rattle;small echo;closing chime;vent whistle|noted;recorded;within the work area;checked at the source;included in the report;listed as intermittent;held for comparison;not an alarm;unchanged at inspection;recorded without comment;excluded from the survey;heard during testing;assigned to maintenance;omitted from the summary;present at reduced load|heard before the switch;returning from the lined wall;listed after the source was removed;quieter in the written copy;continuing between bell notes;recorded by the empty room;missing when the pipe is full;ending at its point of origin;present on the silent test
furniture|spare chair;small desk;side table;bench seat;folding stool;coat stand;low bench;office shelf;empty drawer;desk tray;writing board;plain seat|returned;cleaned;held for collection;listed as surplus;available to reception;checked for wear;assigned to the spare room;not to be moved;marked for repair;included in the inventory;fitted with a new foot;stacked at closing;kept against the wall;awaiting a label;reserved for visitors|returned without being issued;warm in the vacant office;older beneath the new paint;listed in the demolished room;still occupied on the seating plan;facing the removed desk;included twice in the empty tally;missing its place on the floor;waiting in its own crate
labels|green tag;small label;return ticket;blank plate;stock marker;printed strip;red label;paper tag;spare nameplate;room number;side marker;adhesive label|attached;printed;available at stores;returned for correction;checked against the register;issued in duplicate;left blank;marked in pencil;not for reuse;held with the sample;filed as obsolete;copied without color;reserved for the replacement;fixed below the line;approved for removal|naming the empty holder;older than its surface;attached beneath the original;missing from the labelled copy;numbering the erased room;returning with no object;printed on the adhesive side;already worn before issue;referring to the reverse of nothing
mail|internal envelope;return letter;sealed note;office circular;forwarded slip;blank postcard;reply form;delivery notice;unopened letter;small envelope;dispatch card;forwarding note|received;filed;held at reception;returned unopened;approved for circulation;checked for attachments;listed without a sender;available for copying;assigned to dispatch;opened by request;not for forwarding;marked as received;kept with the original;awaiting a reply;copied to the desk|replied to before receipt;addressed to the closed tray;sealed around an absent page;containing the previous envelope;returned by the unused stamp;forwarded to its point of origin;older on the inside;including a reply not requested;delivered beneath the blank address
forms|request sheet;transfer form;blank certificate;claim slip;service form;correction sheet;issue docket;release form;survey sheet;expense slip;amendment form;witness sheet|issued;checked;available at reception;returned unsigned;held pending approval;filed in duplicate;not required for renewals;completed in pencil;listed as provisional;copied on plain paper;reserved for amendments;approved without attachments;supplied on request;withdrawn from circulation;marked for revision|completed before printing;blank beneath the signature;requesting its own withdrawal;approved by the missing box;returned by the empty department;copied without the original;filled on the carbon side only;including an unlisted question;filed as both blank and complete
temperature|bench reading;room temperature;pipe reading;heat entry;surface reading;cooling interval;stored reading;cabinet temperature;air reading;test temperature;warm mark;reference reading|recorded;checked;within the stated range;held for comparison;measured at noon;listed as stable;noted on the test sheet;rounded down;available for review;excluded from the average;returned for confirmation;taken without load;approved for storage;filed under service;unchanged|higher in the empty cupboard;falling before disconnection;warm only on the old sheet;recorded beneath the cooled mark;unchanged after removal;measured in the unused interval;colder behind the sealed panel;retained by the absent surface;correct on neither thermometer
water|lower drain;reserve tank;small valve;return pipe;service tap;water entry;spare basin;overflow line;wet mark;pipe joint;drain cover;level reading|checked;cleared;closed for service;available for testing;held at the stated level;listed on the diagram;measured without flow;marked for repair;fitted with a washer;returned to use;not for drinking;isolated at the valve;recorded at noon;included in the survey;kept covered|full above the empty mark;flowing on the dry diagram;returning without a supply;wet beneath the sealed surface;listed as drained before filling;leaking into the old report;still empty after overflow;measured from the removed bottom;closed only at the source
paint|base coat;orange stripe;spare tin;surface finish;primer layer;edge marking;white patch;test swatch;lower coat;paint entry;dry sample;wall stripe|dry;applied;checked against the sample;held for comparison;marked for recoating;included in the work sheet;available at stores;left unvarnished;approved in daylight;returned to the workshop;listed by finish;kept under cover;not for exterior use;measured at the edge;awaiting a second coat|older than the wall;wet on the archived sample;covering the removed mark;dry beneath the fresh surface;matching an unissued tin;returning after scraping;present only on the reverse;listed before preparation;fading toward the original label
containment|outer seal;chamber register;boundary mark;empty enclosure;service partition;retained barrier;inner plate;release docket;closed section;boundary label;inspection seal;spare partition|checked;recorded;held for review;listed as intact;available for inspection;not to be extended;marked on the plan;secured at closing;returned to maintenance;included in the register;awaiting approval;cleared for cleaning;measured from outside;issued without comment;left in place|intact after removal;closed around an unlisted space;marked on both sides as outer;released without an opening;listed as empty and assigned;holding the previous boundary;returned before installation;sealed beneath its own label;still requiring an exit entry
'''

# These sentences are not runtime templates: all resulting text is shipped static.
# Realizations mix bare fragments, instructions, passive notes, marginal notation,
# labels and complete statements. Each realization has a small corpus quota.
ROUTINE = [
 '{n} {s}.', '{n}: {s}.', '{n} - {s}.', '{n}, {s}.', '{n} / {s}',
 'the {n} is {s}.', 'a {n} is {s}.', '{s}: {n}.', '{s}, the {n}.',
 'leave the {n} {s}.', 'keep the {n} {s}.', 'the {n} remains {s}.',
 '{n} now {s}.', '{n} still {s}.', '{n} currently {s}.',
 'one {n}, {s}.', 'the {n} was {s}.', 'a {n} was {s}.',
 '{n} to be {s}.', '{n} to remain {s}.', 'the {n} may remain {s}.',
 'the {n} must remain {s}.', '{n} should be {s}.', '{n} already {s}.',
 'no change: {n} {s}.', '{n} {s}; no amendment.', '{n} {s}; retain the copy.',
 '{n} {s}; entry complete.', '{n} {s}; no further action.', '{n} {s}; noted in passing.',
 '{n} {s}; ordinary handling.', '{n} {s}; no charge.', '{n} {s}; copy retained.',
 '{n} {s}, as agreed.', '{n} {s}, as supplied.', '{n} {s}, where applicable.',
 '{n} {s}, by arrangement.', '{n} {s}, without comment.', '{n} {s}, for the present.',
 '{n} {s}, pending confirmation.', '{n} {s}, unless amended.',
 '{n} {s}, subject to review.', '{n} {s}, by request.', '{n} {s}, if required.',
 '{n} {s}, without alteration.', '{n} {s}, as previously noted.',
 '{n} {s}, as copied.', '{n} {s}, with the usual reservations.',
 '{n} {s} for now.', '{n} {s} again.', '{n} {s} at last.',
 '{n} {s} until further notice.', '{n} {s} on this occasion.',
 '{n} {s} in the usual manner.', '{n} {s} under the current arrangement.',
 '{n} {s} on the retained sheet.', '{n} {s} by the end of the round.',
 '{n} {s} on the original copy.', '{n} {s} for reference only.',
 '{n} {s}; edition retained.', '{n} {s} on the service copy.',
 '{n} {s} at the time of issue.', '{n} {s} on the opening sheet.',
 '{n} {s}; margin entry.', '{n} {s} on the duplicate.',
 '{n} {s} on the provisional list.', '{n} {s} without a new entry.',
 '{n} {s} at the last review.', '{n} {s} on the returned sheet.',
 '{n} {s} for this round.', '{n} {s} under the revised heading.',
 '{n} {s} on the working copy.', '{n} {s} in the final column.',
 '{n} {s} with approval.', '{n} {s} in the amended list.',
 '{n} {s} at the desk.', '{n} {s} at closing.', '{n} {s} before issue.',
 '{n} {s} after review.', '{n} {s} as recorded.',
]
IRREGULAR = [
 '{n} {s}.', 'the {n} is {s}.', '{n}: {s}.', '{n}, {s}.',
 '{n} still {s}.', '{n} already {s}.', '{n} remains {s}.',
 '{n} {s}; accepted.', '{n} {s}; no correction.', '{n} {s}; carry forward.',
 '{n} {s}; leave the entry.', '{n} {s}; no replacement needed.',
 '{n} {s}; ordinary procedure applies.', '{n} {s}; no objection recorded.',
 '{n} {s}; retained as received.', '{n} {s}, apparently.',
 '{n} {s}; register unchanged.', '{n} {s}, as before.',
 '{n} {s}, without an amendment.', '{n} {s}, again.',
 '{n} {s}, though the copy differs.', '{n} {s}, no longer disputed.',
 '{n} {s}, but the count stands.', '{n} {s}, by mutual agreement.',
 '{n} {s}, for administrative purposes.', '{n} {s}, at least on paper.',
 '{n} {s}, officially.', '{n} {s}, with the entry unchanged.',
 '{n} {s}, on this side.', '{n} {s}, pending no further action.',
 '{n} {s} once more.', '{n} {s} on the new sheet.',
 '{n} {s} in the second reading.', '{n} {s} after the correction.',
 '{n} {s} despite the revised list.', '{n} {s} under the old number.',
 '{n} {s} on the unsigned version.', '{n} {s}; recount accepted.',
 '{n} {s} in the current report.', '{n} {s} with no change of status.',
 '{n} {s} after the form was closed.', '{n} {s} in the retained version.',
 '{n} {s} under the same heading.', '{n} {s} in the original account.',
 '{n} {s} during the unrecorded interval.', '{n} {s} without another issue.',
 '{n} {s} on both copies.', '{n} {s} before the notice.',
 '{n} {s} in the unused column.', '{n} {s} on the corrected sheet.',
 '{n} {s} in the absence of a reply.', '{n} {s} on the previous list.',
 '{n} {s} since the last omission.', '{n} {s} after removal of the heading.',
 '{n} {s} in the margin only.', '{n} {s} where the seal was.',
 '{n} {s} between entries.', '{n} {s} under the blank heading.',
 '{n} {s} until the copy is returned.', '{n} {s} before the first entry.',
]

# Individually authored disturbing fragments; 15 per family. No shared lore.
DISTURBING = r'''
access|admission outlasted the building.;both entrances lead inward.;permission issued to the space between names.;the gate accepted a blank.;no exterior access remains.;clearance for the unlisted side.;entry without an arrival.;a permit for yesterday's room.;the exit was struck from the renewal.;reception recognized the unused pass.;access returned without its door.;the closed gate is on the visitor list.;renewal requires the original absence.;the admission count excludes departures.;authorization found inside the seal.
doors|the hinge belongs to the wall behind it.;closing did not remove the opening.;both faces marked outside.;no return side.;the latch closed before the door.;a handle on the missing surface.;the threshold was moved inward.;the door fits the inventory gap.;the jamb retained the room.;outside hinges, inner lock.;do not close the opening twice.;the spare door arrived with its corridor.;no wall behind the plate.;the removed bolt remains engaged.;an entrance drawn from memory.
rooms|the room remained after unloading.;floor area includes an earlier occupant.;one wall missing from the second survey.;no exterior dimensions.;the ceiling is below the original floor.;this room has no adjacent rooms.;occupancy predates enclosure.;the vacant office needs a departure entry.;the inside was returned separately.;a room retained for its absence.;the annex no longer has an outside.;the floor plan contains the empty plan.;furniture removed, room retained.;the room number is a former measurement.;do not include the room in its own area.
corridors|the route continues through the erasure.;a corridor between two versions of the landing.;distance charged on the return journey.;the passage ends before the last turn.;no far end recorded.;the handrail crosses the missing section.;return route not on this floor.;the hallway retained the departure.;one junction precedes both entrances.;a corner without adjoining walls.;the covered link contains no crossing.;the shorter route took longer to remove.;the passage was surveyed from its absence.;the landing leads to its first copy.;the route sheet has depth.
schedules|the unused shift has been completed.;tomorrow was returned to scheduling.;a break between two copies of noon.;the rota contains no working days.;attendance required during the missing hour.;the schedule resumed before its beginning.;one interval never closed.;the cancelled session is still taking minutes.;no date for the next yesterday.;the end of shift was transferred inward.;all departures booked before opening.;the break outlasted both shifts.;the closure period remains available.;the next round was held last.;time off recorded as a location.
inspections|the inspection found its own completion.;nothing passed the surface check.;the survey counted the unbuilt wall.;wear noted beneath the missing fixture.;the second visit preceded the first fault.;results available inside the sealed instrument.;inspection concluded without an inspected object.;a clean report for the removed room.;the checklist includes its own omission.;the empty space failed twice.;one result remains in the instrument.;the final review has no earlier review.;the surveyor's absence was measured.;no visible surfaces, inspection complete.;the fault was accepted as the witness.
inventory|the empty shelf increased the count.;one absence too many.;nothing returned to stock.;the missing item has a storage weight.;the list contains the shelf it is on.;zero was issued in duplicate.;the final total needs another empty column.;the stockroom is an entry in itself.;the recount found the original count inside.;an unissued absence was returned.;contents excluded from the contents list.;the surplus was measured as a gap.;the tally remains after the ledger is closed.;three missing, none removed.;the blank line has been inventoried.
deliveries|the parcel arrived around the delivery bay.;the sender is the unopened box.;receipt enclosed before arrival.;nothing was packed in two layers.;the consignment contains its own departure.;one delivery is still inside the label.;the empty carton weighs a return journey.;the packing slip is the only arrival.;a destination with no approach.;unpacking left the parcel intact.;the return address was never outside.;the second load did not enter.;the seal encloses the delivery record.;the crate arrived before its contents existed.;the receipt retained the weight.
replacements|the replacement contains the removed part's absence.;the spare was fitted before manufacture.;no original to exchange.;wear transferred to the unopened box.;the new piece remembers a different fixture.;the exchange has no receiving end.;one predecessor still attached.;replacement approved for the empty mount.;the removed part is now the sample.;the spare arrives at its former position.;the new plate covers an earlier new plate.;a fitting for the deleted hole.;the exchange unit has no uninstalled state.;the original is younger on the reverse.;nothing replaced, service restored.
signatures|the blank signed below itself.;witness absent from both copies.;the ink arrived with a departure entry.;one mark covers the unsigned space.;the second hand is not a handover.;signature for an uncreated post.;the countersignature removed the signer.;two approvals, no first mark.;the carbon sheet has the only original.;the witness line continues behind the paper.;signed by the empty field.;the erased initial remains authorized.;the receipt recognizes neither signature.;approval given before the line.;the final mark has no ink allocation.
keys|the key has an interior.;return ring empty, key counted.;a cut for the lock's missing position.;the blank opened before cutting.;the key was recovered from its own outline.;one tooth belongs to an earlier door.;the returned key requires no lock.;the cabinet holds the absence of its key.;the spare was issued from inside the gate.;no outside edge on the brass.;the lock accepted the return entry.;the key tag is the only opening.;a duplicate without a first cut.;the master blank is already worn.;leave the cut unmeasured.
cabinets|the back panel contains the front inventory.;one shelf behind the closed room.;the cupboard opens onto its own label.;contents present beneath the empty mark.;the cabinet was enclosed by its contents.;a drawer assigned to the missing wall.;no rear face in the drawing.;the closed locker has been emptied outward.;shelf depth exceeds cabinet depth.;the hinges attach to an earlier cupboard.;the empty shelf needs a second key.;a cabinet listed under its own contents.;the spare compartment is still arriving.;the door closes behind the inventory.;do not label the back of the empty space.
lights|illumination without an illuminated surface.;the lamp belongs to its reflection.;the spare bulb casts the original room.;light retained after circuit removal.;the shade has no lit side.;a warm outline on the unopened carton.;the pilot light precedes the supply.;brightness assigned to the absent fitting.;the empty socket is the source.;the old diagram remains illuminated.;the lamp count excludes the lights.;one lit entry, no lamp.;the cover darkens the outside only.;the switch controls the previous bulb.;no shadows during the blackout test.
shadows|the shadow is arriving before the geometry.;an outline belonging to no surface.;shade retained in the empty plan.;the shadow crosses the missing wall.;one edge moves against both lights.;the erased shape still has a shadow.;no object behind the dark side.;the shade was returned without its source.;the dark mark has a departure time.;the shadow inventory contains a lamp.;two shadows, one absence.;the shadow's height was measured indoors.;the boundary falls toward the light.;the shade continues under the removed floor.;do not trace the original darkness.
geometry|history contains geometry that no longer exists.;the edge returns through its own length.;the missing face has an area.;an angle between two copies of the same wall.;the outside intersects the inside twice.;no volume enclosed, boundary complete.;the contour belongs to an earlier measurement.;the straight line has a reverse corner.;the gap is load-bearing on the drawing.;the section was cut from its own plan.;a surface without an unpainted side.;depth measured past the original back.;the deleted edge remains adjacent.;one plane occupies the erased plane.;the open shape contains its closure.
history|no initial state in the retained history.;the old copy contains the next removal.;the record precedes its own source.;revision below the blank page.;the discarded layout remained in use.;one earlier version has no date.;the archive retained the future omission.;the amendment removed the original arrival.;history issued without a first entry.;the last copy includes the first copy's absence.;the retained state cannot be returned.;the older tracing has no surface.;nothing changed before its removal.;the superseded plan is still unfolding.;one revision outside the sequence.
frames|one of these frames is lying.;the still image contains a departure.;a held frame from the absent view.;the sample outlasted its source.;no scene behind the retained detail.;the right edge belongs to another copy.;the first image has a previous frame.;a reference captured after disposal.;the empty frame has an exposure.;the image includes the removed interval.;the last sample arrived without light.;one outline not in the geometry.;the spare frame contains the original gap.;no source for the second image.;the comparison returned a third stillness.
presentation|the second present was not ours.;delivered to the gap between outputs.;the front buffer retained a back room.;one visible copy was never submitted.;the delivery interval has an interior.;presentation confirmed before release.;the output arrived after its disappearance.;the queue contains no oldest entry.;two boundaries, one crossing.;a delivery recorded on the source side.;the final output retained the first departure.;the visible copy has no receiving surface.;the slot was occupied before allocation.;one release remains inside the queue.;the boundary returned the delivered frame.
reconstruction|nothing reconstructed, only retained.;the recovered surface remembers an unbuilt wall.;the seam precedes both sides.;reconstruction found the original absence.;one contour not in the reference.;the restored corner has no angle.;a recovered detail without a lost state.;the model contains its removal.;the replacement shape fits the erased source.;the outline was restored from the gap.;the partial model has a complete inside.;no original behind the recovered view.;the reference seam never joined anything.;the restored edge belongs to a later copy.;the reconstruction has no first surface.
maintenance|the work sheet retained the repair.;the fault was serviced before installation.;the bench test contains no bench.;one tool request arrived from the removed fixture.;the cleaning entry has a surface.;repair complete, object absent.;the order remains inside the replacement.;service restored to the vacant mount.;a fault recorded beneath its correction.;the test returned its own work permit.;the estimate exceeds the missing installation.;no repairable state retained.;the adjustment predates the fitting.;a completed job in the blank interval.;the service copy keeps accumulating wear.
time|the minute was filed as a room.;the calendar ends before its first entry.;a date retained outside the schedule.;seconds omitted, interval still increasing.;the unused hour has a closing signature.;the time stamp requires an arrival.;one minute missing from both clocks.;the earlier date was installed afterward.;the clock face contains the gap.;the closing hour remains open.;the reference date has no preceding day.;the appointment returned its own duration.;an interval without elapsed time.;the recorded minute is deeper than the room.;the calendar copy is not chronological.
records|the missing page is the index.;the blank register contains an omission.;a duplicate with no copying history.;the carbon sheet retained the erased original.;the loose entry has an inside margin.;the last receipt is the first record.;the closed file contains its opening.;no blank version of this form.;the withdrawn sheet keeps receiving entries.;one page older than its heading.;the margin note occupies the whole file.;the empty register is signed throughout.;the missing attachment returned the docket.;the record includes its own absence.;two originals beneath the same carbon.
measurements|the ruler was measured from inside.;zero is outside the stated tolerance.;the room was shorter before measurement.;the depth reading contains the instrument.;the missing wall has two widths.;an area beneath the length column.;the reference weight arrived without mass.;the second reading removed the first surface.;the clearance has no adjoining fixtures.;one unit retained after subtraction.;the ceiling height includes the floor below.;the scale measures its own empty pan.;the edge continues past the final mark.;no exterior length for this reading.;the measure returned a smaller room.
staff|the vacant post submitted attendance.;the handover occurred without either shift.;one departure still assigned to reception.;the roster has no unoccupied version.;relief required for the empty desk.;the previous absence covered the late round.;the staff notice signed out first.;the service desk remains in attendance.;a return entered under vacancy.;the temporary post predates its office.;the night desk has no arrival column.;the crew allocation lists the corridor.;the unfilled position is on leave.;the handover contains an extra departure.;attendance closed around a blank name.
weather|rain entered beneath the dry record.;the covered passage contains an outside forecast.;the wind reading came from the sealed room.;frost retained in the warm copy.;the storm interval has a ceiling.;the dry period was returned wet.;cloud record filed as a floor plan.;the pressure reading has a doorway.;sunlight remains on the omitted surface.;the thaw notice precedes the frozen entry.;rain measured behind the original wall.;the clear interval contains no sky.;the weather sheet is wet on the carbon side.;one forecast removed from the ceiling.;the damp report keeps its own temperature.
power|the disconnected circuit has a return load.;the spare cell contains the previous charge.;isolation recorded inside the fuse.;no supply behind the live entry.;the switch is powered by its diagram.;the empty socket draws the missing load.;one circuit returns to its own label.;the breaker retains the discarded feed.;the service line exists on the off side.;the test socket has no isolated state.;the charge record is warmer than the cell.;current listed beneath the erased connection.;the auxiliary supply predates the main line.;the fuse carrier contains the unplugged room.;the reserve circuit was returned live.
storage|the shelf contains its own capacity.;the empty bay has a stored weight.;contents retained after the bin was returned.;a reserve rack behind the inventory.;the sealed tote contains its opening.;the rear store has no exterior access.;one tray stored in the space it left.;the empty container needs unloading.;the packing shelf has a return address.;the lower rack predates the floor.;storage allocated to the missing contents.;the dry store retains an earlier rain entry.;the archive box has no unfolded state.;the return bin contains the issued bin.;the clearance was stored upright.
stairs|the lower flight ends above its beginning.;one tread removed from both directions.;the landing rail returns through the floor.;descent recorded as an extra step.;the upper landing has no approach.;the rear flight contains a previous landing.;a step below the last floor.;the stair bracket supports its own omission.;no lower side to the bottom tread.;the nosing belongs to an unbuilt stair.;the side rail has two inside edges.;the service stair ends on the route sheet.;one landing between duplicate floors.;the ascent was filed under depth.;the removed tread remains under load.
elevators|the car returned without leaving the floor.;the upper stop is inside the indicator.;a load entry for the empty landing.;the lift register has no ground floor.;the service cage contains the route.;the call button precedes its panel.;the car floor remains at both stops.;the spare cable has no upper end.;the return switch called the former lift.;one arrival below the lowest stop.;the landing indicator contains the car.;the inspection lever has an unused direction.;no shaft on the original plan.;the lift arrived at the closed entry.;the car carries the missing floor.
windows|the glass retains the room behind its reflection.;the outer sill belongs to an inside wall.;a pane looking onto its replacement.;the covered window has a departure view.;the blind closes behind the glazing.;the latch has no open position.;the spare glass contains the original outside.;the fixed light overlooks an erased landing.;the frame survives in the unbuilt wall.;no interior side to the reflection.;the lower pane has an upper room.;the closed casement retained the weather.;a window measured from the other window.;the taped outline has no glass allocation.;the view was returned without its opening.
space|the empty recess needs unloading.;the unused corner has a return weight.;a gap allocated beneath its own measurement.;the vacant bay was removed from its contents.;clear space retained as a fixture.;the reserved area contains its boundary.;no empty version of the alcove.;the free margin occupies the original page.;one unmarked area still signed in.;the lower void has a ceiling inspection.;the open section is closed on the plan.;the unused portion contains the rest.;the rear recess is larger than the wall.;a clearance behind the absent object.;the space left before removal.
sounds|the echo belongs to the unopened room.;the silent test retained a bell note.;a relay click before the circuit.;the pipe noise has no route.;one creak in the concrete copy.;the hum remains inside the service entry.;the air hiss has a storage location.;the motor tone precedes the installed motor.;a drain sound from the upper wall.;the loose rattle was returned sealed.;the closing chime has no first note.;the vent whistle contains a second corridor.;sound noted on the removed surface.;the echo has a smaller inside.;the bell note stayed after the bell left.
furniture|the spare chair occupies its inventory entry.;the bench seat has no vacant state.;the drawer contains its own outside.;the desk was returned before the office.;a stool listed under floor area.;the table retains the removed wall.;the coat stand predates the arrival list.;the low bench is longer inside its crate.;the office shelf holds the missing office.;the writing board has a reverse room.;the plain seat remains in attendance.;one chair included in the empty count.;the tray contains the desk's absence.;the returned furniture still requires a departure.;the seat was reserved by the seating plan.
labels|the label names its adhesive side.;the room number has an interior.;the blank plate retained the old name.;the printed strip is older than the object.;the green tag has no unissued state.;the return ticket contains the missing item.;a marker assigned to its removal.;the spare nameplate is already occupied.;the red label continues under the paint.;the paper tag has a storage weight.;the side marker belongs to an absent side.;the label is the only remaining contents.;the blank number was counted twice.;the old heading covers the new surface.;the label returned the original object.
mail|the envelope contains its own outside address.;a reply sent from the unprinted side.;the internal letter never had an inside.;the sealed note has a departure signature.;the circular was returned before circulation.;the forwarding slip is still arriving.;the blank postcard kept the destination.;the dispatch card contains the unopened tray.;the notice has no original delivery.;the return letter remains in its own envelope.;the small envelope is deeper than the letter.;a reply form without a receiving office.;the address was removed from both ends.;the stamp sealed the blank space.;the forwarded note arrived before the route.
forms|the blank certificate has a previous occupant.;the claim slip requests the claimant's absence.;the request sheet contains its own approval.;the transfer form has no receiving column.;the issue docket was filled before printing.;a release form for the unopened space.;the survey sheet includes the instrument.;the amendment has no prior wording.;the expense slip lists the empty interval.;the witness sheet contains no blank line.;the correction removed the original form.;one question has no printed version.;the completed sheet requires an empty copy.;the signature field has a departure date.;the service form returned its issuing desk.
temperature|the warm mark predates the surface.;the cooled reading remains inside the cabinet.;the room temperature has a floor plan.;heat retained after the object was removed.;the pipe reading is colder on the original.;the bench temperature has an arrival entry.;the air reading occupies the sealed gap.;the test temperature exceeds the empty range.;a cooling interval beneath the date.;the stored reading is still warming.;the cabinet retains an unmeasured warmth.;the reference reading has no instrument.;the surface reading came from inside the paper.;one degree assigned to the missing room.;the cold side was removed from the sample.
water|the dry pipe has a return flow.;the level reading includes the empty tank.;a tap supplying its own diagram.;the wet mark has no surface.;the overflow ends above its source.;the basin was returned with its drain.;one valve closed around the original flow.;the reserve tank has no empty state.;the drain cover contains an upper room.;the water entry remains after draining.;the joint is wet on the retained plan.;the lower drain precedes the floor.;the return pipe has no receiving end.;the service tap retained yesterday's level.;the sealed water entry is still filling.
paint|the coat retained the removed surface.;the primer is older than the wall.;a stripe on the inside of the paint.;the dry sample contains a wet interval.;the swatch remembers an unissued color.;the spare tin holds the missing finish.;the orange mark has a departure entry.;the white patch covers the absent plate.;the lower coat has no outer layer.;the test finish includes its own removal.;the edge marking precedes the edge.;the wall stripe was returned separately.;the paint entry retains a different room.;one surface painted before enclosure.;the fresh coat has a previous side.
containment|the seal contains its own inspection.;the enclosure has no released state.;the chamber register lists the empty boundary.;the partition was removed from inside itself.;both sides of the plate are outer.;the release docket has no departure field.;one barrier still retained beneath the gap.;the closed section remains uninstalled.;the boundary mark came with an arrival entry.;the inspection seal is older than the enclosure.;the label holds the previous partition.;no interior on the retained plan.;the chamber has no vacant version.;the empty enclosure requires a return receipt.;containment continues outside the marked section.
'''

HAUNTED = [
 ('doors','some doors stay open.'), ('rooms','there was never a west room.'),
 ('history','this entry has no previous state.'), ('signatures','the empty chamber requires two signatures.'),
 ('inventory','we stopped counting after the first return.'), ('keys','the lock was installed from the inside.'),
 ('access','no one was admitted.'), ('corridors','the shorter way was removed.'),
 ('schedules','the first shift is still here.'), ('inspections','leave this one uninspected.'),
 ('deliveries','nothing else arrived.'), ('replacements','keep the original absence.'),
 ('cabinets','do not open the empty compartment.'), ('lights','the last bulb was never fitted.'),
 ('shadows','the outline has been excused.'), ('geometry','that corner is not part of the room.'),
 ('frames','retain the unrendered copy.'), ('presentation','one delivery has no recipient.'),
 ('reconstruction','not a restored surface.'), ('maintenance','no further repair authorized.'),
 ('time','the hour has no other side.'), ('records','the original was the blank one.'),
 ('measurements','do not measure the remaining space.'), ('staff','the vacancy has been filled in.'),
 ('weather','it was dry in the first account.'), ('power','isolation did not end the supply.'),
 ('storage','contents withheld from the container.'), ('stairs','there is no lower landing.'),
 ('elevators','the car did not return empty.'), ('windows','the outside was not included.'),
 ('space','leave the gap assigned.'), ('sounds','the second sound was not a return.'),
 ('furniture','the chair is no longer an item.'), ('labels','the label is to remain blank.'),
 ('mail','no reply from this side.'), ('forms','do not complete the last field.'),
 ('temperature','still warm beneath the omission.'), ('water','the level was never zero.'),
 ('paint','nothing beneath the first coat.'), ('containment','the boundary has been excused.'),
 ('access','admission is not an arrival.'), ('doors','no open position recorded.'),
 ('rooms','the empty room was not empty.'), ('corridors','the return route was a receipt.'),
 ('schedules','leave the unused day alone.'), ('inspections','the result is not to be kept.'),
 ('inventory','the missing one is not a shortage.'), ('deliveries','do not acknowledge this receipt.'),
 ('replacements','no replacement for the original space.'), ('signatures','both signatures were the first.'),
 ('keys','no key was issued for the exit.'), ('cabinets','the shelf was not inside.'),
 ('lights','nothing was illuminated by that lamp.'), ('shadows','the shade was not a shadow.'),
 ('geometry','the drawing is the remaining wall.'), ('history','no earlier copy will be supplied.'),
 ('frames','this was not a captured image.'), ('presentation','delivery is not evidence of departure.'),
 ('reconstruction','the source never had this edge.'), ('maintenance','leave the completed job open.'),
]
BREACH = [
 ('records','the blank was a carbon copy.'),
 ('space','the inside was the item returned.'),
 ('time','before is not an available location.'),
 ('signatures','the witness was the remaining signature.'),
 ('deliveries','it arrived with the space it had left.'),
 ('containment','the enclosure was listed under contents.'),
]

def norm(s):
 return re.sub(r'\s+',' ',s.lower().strip()).rstrip('.!?:;, -')

def main():
 domains=[line.split('|') for line in DOMAINS.strip().splitlines()]
 disturbing=dict(line.split('|',1) for line in DISTURBING.strip().splitlines())
 assert len(domains)==40 and len(disturbing)==40
 rows=[]; seen=set()
 def add(tier,family,text,form):
  text=text.strip(); key=norm(text)
  if key in seen: return False
  assert text.isascii() and len(text)<=116 and '{' not in text
  seen.add(key)
  rows.append(dict(id=hashlib.sha256(text.encode()).hexdigest()[:16],tier=tier,family=family,text=text,authoring_form=form))
  return True
 # Balanced families avoid the cooldown preferentially filtering a large motif.
 for family_index,(family,objects,states,odd) in enumerate(domains):
  nouns=objects.split(';'); routine=states.split(';'); irregular=odd.split(';')
  include_variants=["entered in the","covered by the","on the","part of the","listed in the","accounted for in the","added to the","noted in the"]
  routine=[state.replace("included in the",include_variants[family_index%len(include_variants)]) for state in routine]
  for tier,quota,bank,forms in [(0,105,routine,ROUTINE),(1,45,irregular,IRREGULAR)]:
   candidates=[(n,s) for n in nouns for s in bank];RNG.shuffle(candidates)
   count=0
   for n,s in candidates:
    form=(count+family_index*37)%len(forms)
    text=forms[form].format(n=n,s=s)
    # Keep most messages brief and avoid long suffix constructions.
    if len(text)>100: continue
    if add(tier,family,text,f'{tier}:{form}'):count+=1
    if count==quota:break
   assert count==quota,(family,tier,count)
  entries=disturbing[family].split(';'); assert len(entries)==15,(family,len(entries))
  for i,text in enumerate(entries):assert add(2,family,text,f'authored:{family}:{i}')
 for i,(f,t) in enumerate(HAUNTED):assert add(3,f,t,f'rare:{i}')
 for i,(f,t) in enumerate(BREACH):assert add(4,f,t,f'breach:{i}')
 # Replace several routine entries with short, separately authored fragments.
 # These are deliberately disconnected, not seed sentences for substitutions.
 shorts='''still warm.|wrong corridor.|three remained.|inventory complete.|outside only.|lower hinge unchanged.|one chair returned.|afternoon access restored.|nothing amended.|not yet dry.|spare retained.|within the margin.|blue ink accepted.|no attachments.|room for one.|empty on receipt.|plain envelope.|leave unpainted.|inspection deferred.|unclaimed since issue.|count before closing.|not a spare.|shelf reserved.|two copies only.|weather permitting.|nothing to forward.|west access restored.|not for loading.|same dimensions.|no charge recorded.|copy held.|seal unbroken.|for stores.|the usual quantity.|one clean side.|fold toward the mark.|no second coat.|not this entrance.|low pressure.|stairs available.|unoccupied at inspection.|bench clear.|returned in person.|no amendment needed.|outward face.|opening postponed.|replacement arrived early.|quarter turn only.|do not stack.|above the line.|ordinary handling.|unlisted but accepted.|measured twice.|nothing changed.|the old bracket fits.|blank reverse.|kept for reference.|not for signature.|supply exhausted.|upper shelf only.|allow to dry.|no receipt needed.|left at reception.|clean before return.|door on the left.|issued without cover.|leave the lower hinge alone.|west stairwell available.|the spare key was returned.|it was quieter before.|leave the latch as found.|one coat sufficient.|as supplied.|no further allocation.|file the spare copy.|not a new issue.|the lower cabinet stays unlocked.|three in reserve.|take the shorter form.|an ordinary return.|the room was measured twice.|do not inventory the empty shelf.|one rabbit omitted from the stock list.|no feeding allowance entered.|the carrot was filed as stationery.|nothing under this heading.|no exterior label.|folded once.|the toolbar was buried.|the settings have taken hold.|do not confuse inactivity with compliance.|08:15 entry retained.|1998-03-12, copy only.|1907-14-08 remains on the unused schedule.|23:61, not for correction.|section 0 follows section 2.|17-b was returned without 17-a.|04:30 opening, as printed.|no item 31 in this edition.|the bell rang at 11:00 on the test sheet.'''.split('|')
 routine_rows=[r for r in rows if r["tier"]==0]
 for i,t in enumerate(shorts):
  old=routine_rows[i*40];seen.remove(norm(old['text']))
  assert norm(t) not in seen;seen.add(norm(t))
  fragment_tags={
   "temperature":["warm","dry","pressure"],"corridors":["corridor"],"inventory":["three","quantity","stock","shelf","count","allocation","surplus"],
   "access":["access","entrance","entry","opening","reception"],"doors":["hinge","latch","door","turn"],"keys":["key"],
   "rooms":["room","unoccupied"],"inspections":["inspection","measured","dimensions"],"furniture":["chair","bench"],
   "signatures":["signature","ink"],"paint":["coat","paint","color"],"mail":["envelope","forward","receipt"],
   "stairs":["stair"],"weather":["weather"],"containment":["rabbit","feeding","carrot","compliance"],
   "time":["08:15","1998-","1907-","23:61","04:30","11:00"],"labels":["label","heading","17-b","section","item 31"],
   "storage":["stores","stack","loading"],"maintenance":["bracket","repair","clean","tools"],"deliveries":["arrived","issued","supplied","returned","replacement"],
  }
  family=next((f for f,words in fragment_tags.items() if any(w in t for w in words)),"records")
  old.update(id=hashlib.sha256(t.encode()).hexdigest()[:16],text=t,family=family,authoring_form=f'fragment:{i}')
 assert len(rows)==6666
 rows.sort(key=lambda r:(r['tier'],r['id']))
 families=sorted({r['family'] for r in rows});family_ids={f:i for i,f in enumerate(families)}
 (ROOT/'haunted-lines.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
 (ROOT/'haunted-lines.txt').write_text('\n'.join(r['text'] for r in rows)+'\n',encoding='utf-8')
 header=['#pragma once','#include <array>','#include <string_view>','#include <cstdint>','namespace chungus_ui {',
 'struct HauntedMessage { uint64_t id; uint8_t tier; uint8_t family; std::string_view text; };',
 'inline constexpr bool hauntedRare(uint8_t tier) { return tier == 3 || tier == 4; }',
 'inline constexpr bool hauntedBlackRed(uint8_t tier) { return tier == 4; }',
 f'inline constexpr std::array<std::string_view,{len(families)}> hauntedFamilies = {{']
 header += [json.dumps(f)+',' for f in families];header+=['};','inline constexpr std::array<HauntedMessage,6666> hauntedMessages = {{']
 header += ['{0x'+r['id']+'ull,'+str(r['tier'])+','+str(family_ids[r['family']])+','+json.dumps(r['text'])+'},' for r in rows]
 header+=['}};','}']
 (ROOT.parent/'src'/'haunted_lines.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
 print('wrote',len(rows),'static fictional messages')

if __name__=='__main__':main()
