#include "chungus_ui.h"
#include "ui_font_metrics.h"
#include "system_ui_font.h"
#include "haunted_lines.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
namespace chungus_ui {
static std::string wrapLabel(const std::string& caption,float available,float size) {
    std::string result;float width=0;size_t start=0;
    while(start<caption.size()) {
        size_t end=caption.find(' ',start);if(end==std::string::npos)end=caption.size();
        auto word=caption.substr(start,end-start);float wordWidth=0;
        for(unsigned char c:word)wordWidth+=uiFontSpacing()[c>=32&&c<=126?c-32:'?'-32]*size;
        float gap=width?uiFontSpacing()[0]*size:0;
        if(width&&width+gap+wordWidth>available){result+='\n';width=0;gap=0;}
        else if(width)result+=' ';
        result+=word;width+=gap+wordWidth;start=end+1;
    }
    return result;
}
std::string wrapHauntedCaption(const std::string& caption){return wrapLabel(caption,223,.85f);}
static Color cream{.96f,.88f,.68f,1},orange{1,.47f,.06f,1},brown{.31f,.13f,.02f,1},white{1,1,.88f,1};
void Panel::quad(Rect r,Color top,Color bottom,Rect uv){if(commands.size()>=8000||r.w<=0||r.h<=0)return;Rect physical{originX+r.x*scale,originY+r.y*scale,r.w*scale,r.h*scale};Rect scissor{originX+clip.x*scale,originY+clip.y*scale,clip.w*scale,clip.h*scale};commands.push_back({physical,uv,scissor,top,bottom});}
void Panel::fill(Rect r,Color c){quad(r,c,c);}
void Panel::bevel(Rect r,bool inset,Color top,Color bottom){quad(r,top,bottom);auto hi=inset?brown:white;auto lo=inset?white:brown;fill({r.x,r.y,r.w,2},hi);fill({r.x,r.y,2,r.h},hi);fill({r.x,r.y+r.h-2,r.w,2},lo);fill({r.x+r.w-2,r.y,2,r.h},lo);}
void Panel::text(float x,float y,const std::string& value,Color color,float size){float start=x;unsigned count=0;int role=size>1.1f?1:size<.8f?2:size<.95f?3:size>1.01f?4:0;for(unsigned char c:value){if(++count>1200)break;if(c=='\n'){x=start;y+=18*size;continue;}if(c<32||c>126)c='?';int n=c-32;quad({x,y,24/1.35f,28/1.35f},color,color,{float(n%42)*24/1024,float(role*84+n/42*28)/1024,24.f/1024,28.f/1024});commands.back().rect.x=std::round(commands.back().rect.x);commands.back().rect.y=std::round(commands.back().rect.y);commands.back().rect.w=std::round(commands.back().rect.w);commands.back().rect.h=std::round(commands.back().rect.h);x+=uiFontSpacing()[n]*size;}}
void Panel::group(Rect r,const char* label){bevel(r,true,cream,cream);fill({r.x+10,r.y-6,float(std::string(label).size())*7+10,19},cream);text(r.x+15,r.y-6,label,brown);}
void Panel::light(float x,float y,bool on){bevel({x,y,12,12},true);fill({x+3,y+3,6,6},on?Color{.28f,.75f,.03f,1}:Color{.9f,.13f,.02f,1});}
bool Panel::hit(int item,Rect r,const char* tooltip,bool disabled){bool hover=r.contains(input.x,input.y);if(hover&&!disabled&&!popup){hovered=item;tip=tooltip;}if(disabled)return false;if(popup&&popup!=item)return false;if(hover&&input.pressed){pressedId=item;focus=item;}bool clicked=input.released&&pressedId==item&&hover;if(input.released&&pressedId==item)pressedId=0;return clicked||(focus==item&&input.enter&&!popup);}
bool Panel::button(Rect r,const char* label,const char* tooltip,bool important,bool disabled){int item=++id;bool pressed=pressedId==item&&input.down;bool hover=r.contains(input.x,input.y)&&!popup;auto t=important?orange:Color{.93f,.87f,.75f,1};auto b=important?Color{.76f,.25f,.01f,1}:Color{.7f,.65f,.55f,1};if(hover&&!disabled)t={1,.86f,.32f,1};bevel(r,pressed,t,b);if(focus==item) {fill({r.x+4,r.y+4,r.w-8,1},brown);fill({r.x+4,r.y+r.h-5,r.w-8,1},brown);}text(r.x+10+(pressed?1:0),r.y+(r.h-18)/2+(pressed?1:0),label,disabled?Color{.52f,.46f,.37f,1}:brown,important?1.15f:1.f);return hit(item,r,tooltip,disabled);}
bool Panel::check(Rect r,const char* label,bool& value,const char* tooltip,bool disabled,bool darkTooltip){int item=++id;bevel({r.x,r.y+3,17,17},true,{1,.98f,.86f,1},{1,.98f,.86f,1});if(value){fill({r.x+4,r.y+7,9,9},disabled?Color{.55f,.51f,.42f,1}:brown);}text(r.x+25,r.y+2,label,disabled?Color{.5f,.43f,.33f,1}:brown);if(focus==item)fill({r.x+24,r.y+20,r.w-24,1},brown);bool clicked=hit(item,r,tooltip,disabled);if(hovered==item)darkTip=darkTooltip;if(clicked){value=!value;return true;}return false;}
void Panel::combo(Rect r,int& selected,const std::vector<std::string>& items,const char* tooltip){int item=++id;selected=std::clamp(selected,0,int(items.size())-1);bevel(r,true,{1,.98f,.89f,1},{1,.98f,.89f,1});auto oldClip=clip;clip={r.x+3,r.y+3,r.w-30,r.h-6};text(r.x+8,r.y+6,items[selected]);clip=oldClip;bevel({r.x+r.w-25,r.y+3,22,r.h-6},popup==item);text(r.x+r.w-20,r.y+6,"v");if(focus==item)fill({r.x+6,r.y+r.h-5,r.w-36,1},brown);bool justOpened=false;if(hit(item,r,tooltip)){justOpened=popup!=item;popup=popup==item?0:item;}if(popup==item){popupValue=&selected;popupItems=items;float height=float(items.size())*27+4;popupRect={r.x,r.y+r.h,r.w,height};if(popupRect.y+height>600)popupRect.y=r.y-height;if(input.up)selected=(selected+int(items.size())-1)%int(items.size());if(input.below)selected=(selected+1)%int(items.size());if(input.enter&&!justOpened)popup=0;}}
void Panel::finishPopup(){if(!popup||!popupValue)return;auto old=clip;clip={0,0,720,610};bevel(popupRect,true,{1,.98f,.89f,1},{1,.98f,.89f,1});for(size_t i=0;i<popupItems.size();i++){Rect row{popupRect.x+3,popupRect.y+2+float(i)*27,popupRect.w-6,27};bool hover=row.contains(input.x,input.y);if(hover||int(i)==*popupValue)fill(row,{.96f,.46f,.05f,1});text(row.x+6,row.y+5,popupItems[i]);if(hover&&input.released){*popupValue=int(i);popup=0;pressedId=0;}}if(input.pressed&&!popupRect.contains(input.x,input.y)&&pressedId!=popup)popup=0;clip=old;}
void Panel::finishTooltip(){if(hovered!=lastHovered){lastHovered=hovered;hoverSince=input.time;}if(!hovered||tip.empty()||input.time-hoverSince<.6||popup)return;auto old=clip;clip={0,0,720,610};float w=std::min(440.f,float(tip.size())*6.8f+16);auto caption=wrapLabel(tip,w-16,1);float h=16+18*float(1+std::count(caption.begin(),caption.end(),'\n'));Rect r{std::clamp(input.x+16,8.f,712-w),std::clamp(input.y+22,8.f,602-h),w,h};if(darkTip){fill(r,{0,0,0,1});}else bevel(r,false,{1,1,.7f,1},{1,.93f,.45f,1});auto sc=clip;clip={r.x+4,r.y+4,r.w-8,r.h-8};text(r.x+8,r.y+8,caption,darkTip?Color{1,0,0,1}:Color{.19f,.12f,.06f,1});clip=sc;clip=old;}
Actions Panel::frame(Model& m,const Input& raw,unsigned width,unsigned height){Actions a;const Model before=m;screenW=width;screenH=height;scale=std::clamp(std::min((width-20.f)/720,(height-20.f)/610),.2f,1.35f);originX=std::clamp(originX,5.f,std::max(5.f,width-720*scale-5));originY=std::clamp(originY,5.f,std::max(5.f,height-610*scale-5));input=raw;input.x=(raw.x-originX)/scale;input.y=(raw.y-originY)/scale;commands.clear();id=0;hovered=0;tip.clear();darkTip=false;popupValue=nullptr;clip={-4,-4,728,618};if(input.tab){focus=((focus-1+(input.shift?-1:1)+previousCount)%previousCount)+1;popup=0;}if(raw.pressed&&Rect{0,0,675,32}.contains(input.x,input.y)){drag=true;dragX=raw.x-originX;dragY=raw.y-originY;}if(drag&&raw.down){originX=std::clamp(raw.x-dragX,5.f,std::max(5.f,width-720*scale-5));originY=std::clamp(raw.y-dragY,5.f,std::max(5.f,height-610*scale-5));}if(raw.released)drag=false;
fill({5,5,720,610},{0,0,0,.5f});bevel({0,0,720,610},false,{.98f,.61f,.2f,1},{.82f,.36f,.06f,1});quad({4,4,712,32},{.94f,.43f,.02f,1},{.42f,.12f,.01f,1});text(12,10,"CHUNGUSWARE RTX ENHANCER",white,1.15f);if(button({680,7,30,25},"x","close the window. the rabbit stays in the walls."))a.close=true;
text(13,45,"advanced ai graphics enhancement / entity containment",brown);text(559,45,"build 2007.42",brown);bevel({12,69,696,29},true,cream,cream);light(22,78,m.rrActive);text(42,75,m.rrActive?"nvidia status: chunged / rr preset f":"nvidia status: rr pending / sr fallback");text(510,75,"the toolbar was buried");
if(page==0){group({15,119,416,123},"the reconstruction of rays");text(29,139,"renderer");combo({29,178,377,33},m.renderer,{"vanilla","raw lighting","ray reconstruction"},"raw lighting: see what the denoiser was hiding from you.");text(29,215,"preset f: the others were less cooperative");group({15,264,416,98},"internal res");combo({29,283,377,33},m.resolution,{"fraudulent dlaa (99.9%)","quality","balanced / minecraft default","performance","ultra performance","caca mode (144p)"},m.resolution==0?"fraudulent dlaa lore: the last pixel caused problems":"changes ray-render resolution. the monitor is spared.");text(29,329,m.dimensions);group({15,384,416,135},"spiritually generated frames");std::vector<std::string> multipliers{"off","2x","3x","4x","5x","6x"};multipliers.resize(std::clamp(m.maximumFg+1,1,6));combo({29,405,377,33},m.fg,multipliers,"do not rapidly move the menu while enabled. apparitions may appear");bool reflex=m.fg>0;check({29,450,377,25},"reflex: automatic with fg (required)",reflex,"partial reflex integration. not every delay can be exorcised.",true);text(29,484,"its real performance trust me bro");group({449,119,254,316},"chungus containment chamber");quad({462,133,228,253},white,white,{0,448.f/1024,float(logoWidth)/1024,float(logoHeight)/1024});bevel({461,391,230,30},true,{.96f,.79f,.24f,1},{.96f,.79f,.24f,1});text(469,397,"do not confuse inactivity with compliance.",brown,.78f);Rect messageBox{458,442,237,62};bool rare=hauntedBlackRed(static_cast<uint8_t>(m.rabbitTier));if(rare)fill(messageBox,{0,0,0,1});else bevel(messageBox,false,{1,1,.7f,1},{1,.93f,.45f,1});auto messageClip=clip;clip={465,447,223,54};text(465,447,wrapHauntedCaption(m.rabbitMessage),rare?Color{1,0,0,1}:Color{.19f,.12f,.06f,1},.85f);clip=messageClip;}
else{group({15,119,416,184},"advanced containment settings");text(29,139,"presentation scheduling");combo({29,159,377,33},m.pacing,{"nvidia managed / auto","steady cadence","uncapped / diagnostic"},"i probably wouldnt touch this if i were you");char target[80];std::snprintf(target,sizeof(target),"target presented fps: %.0f (0 = display)",m.target);text(29,205,target);if(button({29,234,56,28},"-","ten fewer frames. they know which ones you chose."))m.target=std::max(0.f,m.target-10);if(button({91,234,56,28},"+","summon ten more frames. no names, please."))m.target=std::min(1000.f,m.target+10);if(button({156,234,115,28},"display auto","use detected refresh. trust the living monitor."))m.target=0;group({15,327,416,112},"exposure input (keep a light on)");combo({29,351,377,33},m.domain,{"original input + brightness correction","scene lighting","native lighting"},"first option: validated exposure. the shadows stay honest.");text(29,401,"custom resolution: sealed below the floorboards");group({449,119,254,320},"runtime / witness statements");auto old=clip;clip={458,136,237,292};float y=138;for(const auto& row:m.diagnostics){text(458,y,row);y+=18;}clip=old;group({15,460,688,61},"current runtime transmission");auto saved=clip;clip={27,478,665,35};text(29,480,m.status);clip=saved;}
if(page==0)check({458,508,235,22},"remember settings",m.remember,"some doors stay open.",false,true);
bevel({16,542,294,48},false,orange,{.75f,.26f,.01f,1});text(27,549,"status: the settings have taken hold",brown,1.05f);text(27,569,"changes apply immediately. stay near the light.",brown,.85f);if(button({320,552,190,35},page?"< main rabbit panel":"witness protection","diagnostics. count the frames, then count them again.")){page=1-page;popup=0;focus=1;}if(button({522,552,180,35},"close (f8 / esc)","return to your world. ignore the footsteps behind you."))a.close=true;text(18,596,"tab: focus  |  enter: activate  |  arrows: dropdowns  |  do not answer the third knock",brown,.85f);
previousCount=std::max(id,1);focus=std::clamp(focus,1,previousCount);finishPopup();finishTooltip();clip={-originX/scale,-originY/scale,float(width)/scale,float(height)/scale};fill({input.x,input.y,3,15},white);fill({input.x+3,input.y+3,3,9},brown);fill({input.x+6,input.y+6,3,3},brown);a.apply=m.resolution!=before.resolution||m.renderer!=before.renderer||m.fg!=before.fg||m.pacing!=before.pacing||m.target!=before.target||m.domain!=before.domain;return a;}
}
