#include "chungus_ui_renderer.h"
#include "probe_gpu.h"
#include <chrono>
#include <thread>
#include <iostream>
using namespace reshade::api;
static chungus_ui::Renderer ui;static chungus_ui::Panel panel;static unsigned callbacks=0;static std::string failure;
static void draw(effect_runtime* runtime){chungus_ui::Model model;model.rrActive=true;model.dimensions="1707 x 960 -> 2560 x 1440";chungus_ui::Input input;uint32_t width,height;runtime->get_screenshot_width_and_height(&width,&height);panel.frame(model,input,width,height);if(!ui.present(runtime,panel.quads(),GetModuleHandleW(nullptr)))failure=ui.error;callbacks++;}
static void destroy(effect_runtime*){ui.release();}
int wmain(int argc,wchar_t** argv){try{
    auto report=argc>1?std::filesystem::path(argv[1]):L"ui-gpu-results";std::filesystem::create_directories(report);
    if(!reshade::register_addon(GetModuleHandleW(nullptr),GetModuleHandleW(L"dxgi.dll")))throw std::runtime_error("ReShade addon registration failed");
    reshade::register_event<reshade::addon_event::reshade_present>(&draw);reshade::register_event<reshade::addon_event::destroy_effect_runtime>(&destroy);
    ComPtr<ID3D12Debug> debug;check(D3D12GetDebugInterface(IID_PPV_ARGS(&debug)),"Debug");debug->EnableDebugLayer();
    Gpu g;ComPtr<IDXGIFactory6> factory;check(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"Factory");ComPtr<IDXGIAdapter1> adapter;check(factory->EnumAdapterByGpuPreference(0,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&adapter)),"Adapter");check(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&g.device)),"Device");
    D3D12_COMMAND_QUEUE_DESC desc{};check(g.device->CreateCommandQueue(&desc,IID_PPV_ARGS(&g.queue)),"Queue");check(g.device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&g.allocator)),"Allocator");check(g.device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,g.allocator.Get(),nullptr,IID_PPV_ARGS(&g.list)),"List");check(g.device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&g.fence)),"Fence");
    WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"ChungusWareOwnedUiTest";RegisterClassW(&wc);HWND window=CreateWindowW(wc.lpszClassName,L"ChungusWare UI GPU validation",WS_OVERLAPPEDWINDOW,50,50,1060,920,nullptr,nullptr,wc.hInstance,nullptr);if(argc<3||std::wstring(argv[2])!=L"--hidden")ShowWindow(window,SW_SHOW);
    DXGI_SWAP_CHAIN_DESC1 swapDesc{};swapDesc.Width=1060;swapDesc.Height=920;swapDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;swapDesc.SampleDesc.Count=1;swapDesc.BufferCount=3;swapDesc.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;swapDesc.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;ComPtr<IDXGISwapChain1> swap;check(factory->CreateSwapChainForHwnd(g.queue.Get(),window,&swapDesc,nullptr,nullptr,&swap),"Swapchain");ComPtr<IDXGISwapChain3> chain;check(swap.As(&chain),"Swapchain3");
    D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;hd.NumDescriptors=3;ComPtr<ID3D12DescriptorHeap> rtvs;check(g.device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&rtvs)),"RTV heap");std::array<ComPtr<ID3D12Resource>,3> buffers;auto increment=g.device->GetDescriptorHandleIncrementSize(hd.Type);for(unsigned n=0;n<3;n++){check(chain->GetBuffer(n,IID_PPV_ARGS(&buffers[n])),"Buffer");auto cpu=rtvs->GetCPUDescriptorHandleForHeapStart();cpu.ptr+=n*increment;g.device->CreateRenderTargetView(buffers[n].Get(),nullptr,cpu);}
    unsigned last=0;for(unsigned frame=0;frame<60;frame++){if(frame==20||frame==40){g.submit();ui.release();buffers={};check(chain->ResizeBuffers(3,frame==20?800:1060,frame==20?700:920,swapDesc.Format,0),"Resize");for(unsigned n=0;n<3;n++){check(chain->GetBuffer(n,IID_PPV_ARGS(&buffers[n])),"Resized buffer");auto handle=rtvs->GetCPUDescriptorHandleForHeapStart();handle.ptr+=n*increment;g.device->CreateRenderTargetView(buffers[n].Get(),nullptr,handle);}}MSG msg;while(PeekMessageW(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessageW(&msg);}last=chain->GetCurrentBackBufferIndex();auto cpu=rtvs->GetCPUDescriptorHandleForHeapStart();cpu.ptr+=last*increment;D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={buffers[last].Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_RENDER_TARGET};g.list->ResourceBarrier(1,&b);float clear[]={.12f,.14f,.16f,1};g.list->ClearRenderTargetView(cpu,clear,0,nullptr);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);g.list->ResourceBarrier(1,&b);g.submit();check(chain->Present(0,0),"Present");std::this_thread::sleep_for(std::chrono::milliseconds(8));}
    if(!callbacks||!failure.empty())throw std::runtime_error(failure.empty()?"UI draw callback did not run":failure);
    auto target=buffers[last].Get();auto rd=target->GetDesc();D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT64 bytes=0;g.device->GetCopyableFootprints(&rd,0,1,0,&footprint,nullptr,nullptr,&bytes);auto read=buffer(g.device.Get(),bytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={target,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_COPY_SOURCE};g.list->ResourceBarrier(1,&b);D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=read.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=footprint;src.pResource=target;src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;g.list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);g.list->ResourceBarrier(1,&b);g.submit();void* data=nullptr;check(read->Map(0,nullptr,&data),"Readback");std::ofstream pixels(report/L"ui-gpu.rgba",std::ios::binary);for(unsigned y=0;y<920;y++)pixels.write(static_cast<char*>(data)+footprint.Offset+y*footprint.Footprint.RowPitch,1060*4);pixels.close();read->Unmap(0,nullptr);
    unsigned errors=0;ComPtr<ID3D12InfoQueue> info;if(SUCCEEDED(g.device.As(&info)))for(UINT64 n=0;n<info->GetNumStoredMessages();n++){SIZE_T size=0;info->GetMessage(n,nullptr,&size);std::vector<char> bytes(size);auto m=reinterpret_cast<D3D12_MESSAGE*>(bytes.data());info->GetMessage(n,m,&size);if(m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){errors++;std::cerr<<m->pDescription<<'\n';}}
    std::ofstream(report/L"ui-gpu.json")<<"{\"reshade_callbacks\":"<<callbacks<<",\"resize_cycles\":2,\"debug_errors\":"<<errors<<",\"renderer\":\"owned atlas/shaders/root-constant quads\",\"minecraft_verified\":false}";if(errors)throw std::runtime_error("D3D12 validation errors");
    buffers={};chain.Reset();swap.Reset();DestroyWindow(window);std::cout<<"Owned UI GPU + ReShade test passed, callbacks "<<callbacks<<", validation errors 0.\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
