#include "probe_gpu.h"
#include <DirectXMath.h>
#include <sl.h>
#include <sl_dlss_g.h>
#include <sl_reflex.h>
#include <sl_pcl.h>
#include <chrono>
std::ofstream* slRuntimeLog=nullptr;void runtimeLog(sl::LogType,const char* message){if(slRuntimeLog){*slRuntimeLog<<message<<std::endl;}}
int wmain(int argc,wchar_t** argv){
 auto dir=std::filesystem::absolute(argc>1?argv[1]:L"managed-fg");std::filesystem::create_directories(dir);std::ofstream log(dir/L"calls.jsonl"),runtimeOutput(dir/L"sl-runtime.log");slRuntimeLog=&runtimeOutput;
 auto call=[&](const char* name,sl::Result r){log<<"{\"call\":\""<<name<<"\",\"result\":"<<unsigned(r)<<"}\n";log.flush();if(r!=sl::Result::eOk)throw std::runtime_error(name);};
 try{
    wchar_t exe[32768]{};GetModuleFileNameW(nullptr,exe,32768);auto path=std::filesystem::path(exe).parent_path().wstring();auto logs=(dir/L"sl").wstring();const wchar_t* paths[]={path.c_str()};sl::Feature features[]={sl::kFeatureDLSS_G,sl::kFeatureReflex,sl::kFeaturePCL};sl::Preferences pref{};pref.flags=sl::PreferenceFlags::eDisableCLStateTracking|sl::PreferenceFlags::eUseFrameBasedResourceTagging;pref.pathsToPlugins=paths;pref.numPathsToPlugins=1;pref.pathToLogsAndData=logs.c_str();pref.featuresToLoad=features;pref.numFeaturesToLoad=3;pref.applicationId=0;pref.projectId="f68a0a36-9374-4e5b-b62f-d55f5d6c7810";pref.engineVersion="0.1.0";pref.logMessageCallback=&runtimeLog;pref.logLevel=sl::LogLevel::eVerbose;call("slInit",slInit(pref,sl::kSDKVersion));
    ComPtr<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();
    Gpu g;ComPtr<IDXGIFactory6> factory;check(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"Factory");ComPtr<IDXGIAdapter1> adapter;check(factory->EnumAdapterByGpuPreference(0,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&adapter)),"Adapter");DXGI_ADAPTER_DESC1 ad{};adapter->GetDesc1(&ad);sl::AdapterInfo ai{};ai.deviceLUID=reinterpret_cast<uint8_t*>(&ad.AdapterLuid);ai.deviceLUIDSizeInBytes=sizeof(LUID);call("slIsFeatureSupported(DLSS_G)",slIsFeatureSupported(sl::kFeatureDLSS_G,ai));check(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&g.device)),"Device");ID3D12Device* nativeDevice=nullptr;call("slGetNativeInterface(device)",slGetNativeInterface(g.device.Get(),reinterpret_cast<void**>(&nativeDevice)));call("slSetD3DDevice",slSetD3DDevice(nativeDevice));nativeDevice->Release();
    ID3D12Device* proxy=g.device.Get();proxy->AddRef();call("slUpgradeInterface(device)",slUpgradeInterface(reinterpret_cast<void**>(&proxy)));ComPtr<ID3D12Device> proxyDevice;proxyDevice.Attach(proxy);D3D12_COMMAND_QUEUE_DESC q{};check(proxy->CreateCommandQueue(&q,IID_PPV_ARGS(&g.queue)),"Queue");check(g.device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&g.allocator)),"Allocator");check(g.device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,g.allocator.Get(),nullptr,IID_PPV_ARGS(&g.list)),"List");check(g.device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&g.fence)),"Fence");
    IDXGIFactory6* pf=factory.Detach();call("slUpgradeInterface(factory)",slUpgradeInterface(reinterpret_cast<void**>(&pf)));factory.Attach(pf);
    WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"ManagedFGTest";RegisterClassW(&wc);HWND hwnd=CreateWindowW(wc.lpszClassName,L"NVIDIA Managed FG Test",WS_OVERLAPPEDWINDOW,0,0,960,540,nullptr,nullptr,wc.hInstance,nullptr);ShowWindow(hwnd,SW_SHOW);auto foregroundThread=GetWindowThreadProcessId(GetForegroundWindow(),nullptr);AttachThreadInput(GetCurrentThreadId(),foregroundThread,TRUE);SetForegroundWindow(hwnd);SetFocus(hwnd);AttachThreadInput(GetCurrentThreadId(),foregroundThread,FALSE);
    DXGI_SWAP_CHAIN_DESC1 desc{};desc.Width=960;desc.Height=540;desc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;desc.SampleDesc.Count=1;desc.BufferCount=3;desc.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;desc.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;ComPtr<IDXGISwapChain1> swap;check(factory->CreateSwapChainForHwnd(g.queue.Get(),hwnd,&desc,nullptr,nullptr,&swap),"Swapchain");ComPtr<IDXGISwapChain3> chain;check(swap.As(&chain),"Swapchain3");
    sl::ReflexOptions ro{};ro.mode=sl::ReflexMode::eLowLatency;call("slReflexSetOptions",slReflexSetOptions(ro));sl::ViewportHandle viewport(0);sl::DLSSGOptions go{};go.mode=argc>2&&_wtoi(argv[2])?sl::DLSSGMode::eOn:sl::DLSSGMode::eOff;go.numFramesToGenerate=argc>2?std::max(1,_wtoi(argv[2])):1;go.numBackBuffers=3;go.mvecDepthWidth=640;go.mvecDepthHeight=360;go.colorWidth=960;go.colorHeight=540;go.colorBufferFormat=DXGI_FORMAT_R8G8B8A8_UNORM;go.mvecBufferFormat=DXGI_FORMAT_R32G32_FLOAT;go.depthBufferFormat=DXGI_FORMAT_R32_FLOAT;call("slDLSSGSetOptions",slDLSSGSetOptions(viewport,go));
    auto depth=texture(g.device.Get(),640,360,DXGI_FORMAT_R32_FLOAT),motion=texture(g.device.Get(),640,360,DXGI_FORMAT_R32G32_FLOAT);std::vector<float> zs(640*360,.5f),mvs(640*360*2,0.f);auto up1=upload(g,depth.Get(),zs,1),up2=upload(g,motion.Get(),mvs,2);g.submit();
    using namespace DirectX;sl::Constants c{};auto set=[](sl::float4x4& out,FXMMATRIX m){XMFLOAT4X4 v;XMStoreFloat4x4(&v,m);memcpy(&out,&v,64);};auto proj=XMMatrixPerspectiveFovLH(1.f,960.f/540,.1f,1000.f);set(c.cameraViewToClip,proj);set(c.clipToCameraView,XMMatrixInverse(nullptr,proj));set(c.clipToPrevClip,XMMatrixIdentity());set(c.prevClipToClip,XMMatrixIdentity());set(c.clipToLensClip,XMMatrixIdentity());c.cameraPinholeOffset={0,0};c.jitterOffset={0,0};c.mvecScale={1,1};c.cameraPos={0,0,0};c.cameraUp={0,1,0};c.cameraRight={1,0,0};c.cameraFwd={0,0,1};c.cameraNear=.1f;c.cameraFar=1000;c.cameraFOV=1;c.cameraAspectRatio=960.f/540;c.depthInverted=sl::eFalse;c.cameraMotionIncluded=sl::eTrue;c.motionVectors3D=sl::eFalse;c.reset=sl::eTrue;
    sl::Resource dz{sl::ResourceType::eTex2d,depth.Get(),nullptr,nullptr,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE},mv{sl::ResourceType::eTex2d,motion.Get(),nullptr,nullptr,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE};sl::Extent extent{0,0,640,360};sl::ResourceTag tags[]={{&dz,sl::kBufferTypeDepth,sl::ResourceLifecycle::eValidUntilPresent,&extent},{&mv,sl::kBufferTypeMotionVectors,sl::ResourceLifecycle::eValidUntilPresent,&extent}};
    D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_RTV,1};ComPtr<ID3D12DescriptorHeap> heap;check(g.device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)),"RTV heap");unsigned actual=0;auto begin=std::chrono::steady_clock::now();
    for(uint32_t frame=0;frame<120;frame++){
        MSG msg;while(PeekMessageW(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessageW(&msg);}sl::FrameToken* token=nullptr;call("slGetNewFrameToken",slGetNewFrameToken(token,&frame));call("slReflexSleep",slReflexSleep(*token));Sleep(10);c.reset=frame==0?sl::eTrue:sl::eFalse;call("slSetConstants",slSetConstants(c,*token,viewport));call("slSetTagForFrame",slSetTagForFrame(*token,viewport,tags,2,g.list.Get()));
        ComPtr<ID3D12Resource> bb;check(chain->GetBuffer(chain->GetCurrentBackBufferIndex(),IID_PPV_ARGS(&bb)),"Backbuffer");auto rtv=heap->GetCPUDescriptorHandleForHeapStart();g.device->CreateRenderTargetView(bb.Get(),nullptr,rtv);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={bb.Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_RENDER_TARGET};g.list->ResourceBarrier(1,&b);float clear[]={.2f,.3f,.4f,1};g.list->ClearRenderTargetView(rtv,clear,0,nullptr);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);g.list->ResourceBarrier(1,&b);g.submit();call("present_start",slPCLSetMarker(sl::PCLMarker::ePresentStart,*token));check(chain->Present(1,0),"Present");call("present_end",slPCLSetMarker(sl::PCLMarker::ePresentEnd,*token));sl::DLSSGState state{};call("slDLSSGGetState",slDLSSGGetState(viewport,state,nullptr));actual+=state.numFramesActuallyPresented;if(frame==119)log<<"{\"dlssg_status\":"<<unsigned(state.status)<<",\"max\":"<<state.numFramesToGenerateMax<<",\"vsync_supported\":"<<int(state.bIsVsyncSupportAvailable)<<"}\n";
    }
    auto secs=std::chrono::duration<double>(std::chrono::steady_clock::now()-begin).count();std::ofstream(dir/L"result.json")<<"{\"rendered_fps\":"<<120/secs<<",\"presented_fps\":"<<actual/secs<<",\"actual_presentations\":"<<actual<<"}\n";go.mode=sl::DLSSGMode::eOff;slDLSSGSetOptions(viewport,go);slShutdown();DestroyWindow(hwnd);return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
}
