#include "probe_gpu.h"
#include "resolution_modes.h"
int wmain(int argc,wchar_t** argv){try{
    std::filesystem::path report=argc>1?argv[1]:L".";std::filesystem::create_directories(report);
    ComPtr<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();
    Gpu g;ComPtr<IDXGIFactory6> factory;check(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"Factory");ComPtr<IDXGIAdapter1> adapter;
    for(UINT i=0;factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&adapter))!=DXGI_ERROR_NOT_FOUND;i++){DXGI_ADAPTER_DESC1 desc{};adapter->GetDesc1(&desc);if(desc.VendorId==0x10de&&SUCCEEDED(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&g.device))))break;adapter.Reset();}if(!g.device)throw std::runtime_error("No NVIDIA device");
    D3D12_COMMAND_QUEUE_DESC q{};check(g.device->CreateCommandQueue(&q,IID_PPV_ARGS(&g.queue)),"Queue");check(g.device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&g.allocator)),"Allocator");check(g.device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,g.allocator.Get(),nullptr,IID_PPV_ARGS(&g.list)),"List");check(g.device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&g.fence)),"Fence");
    wchar_t exe[32768]{};GetModuleFileNameW(nullptr,exe,32768);auto dir=std::filesystem::path(exe).parent_path();Backend rr;if(!rr.initialize(g.device.Get(),dir,report/L"ngx-logs"))throw std::runtime_error(rr.error());
    auto activation=LoadLibraryW((dir/L"bedrock_rr_activation.dll").c_str());auto start=activation?reinterpret_cast<bool(*)()>(GetProcAddress(activation,"NgxActivationStart")):nullptr;auto qualityStart=activation?reinterpret_cast<bool(*)()>(GetProcAddress(activation,"NgxQualityStart")):nullptr;auto select=activation?reinterpret_cast<bool(*)(int)>(GetProcAddress(activation,"NgxQualitySelect")):nullptr;
    if(!start||!start())throw std::runtime_error("Activation startup failed");
    auto qualityModule=LoadLibraryW((dir/L"bedrock_rr_quality.dll").c_str());qualityStart=qualityModule?reinterpret_cast<bool(*)()>(GetProcAddress(qualityModule,"NgxQualityStart")):nullptr;select=qualityModule?reinterpret_cast<bool(*)(int)>(GetProcAddress(qualityModule,"NgxQualitySelect")):nullptr;
    if(!qualityStart||!qualityStart()||!select)throw std::runtime_error("Quality controller startup failed");
    auto ngx=GetModuleHandleW(L"_nvngx.dll");auto caps=reinterpret_cast<decltype(&NVSDK_NGX_D3D12_GetCapabilityParameters)>(GetProcAddress(ngx,"NVSDK_NGX_D3D12_GetCapabilityParameters"));auto create=reinterpret_cast<decltype(&NVSDK_NGX_D3D12_CreateFeature)>(GetProcAddress(ngx,"NVSDK_NGX_D3D12_CreateFeature"));auto evaluate=reinterpret_cast<decltype(&NVSDK_NGX_D3D12_EvaluateFeature)>(GetProcAddress(ngx,"NVSDK_NGX_D3D12_EvaluateFeature"));auto release=reinterpret_cast<decltype(&NVSDK_NGX_D3D12_ReleaseFeature)>(GetProcAddress(ngx,"NVSDK_NGX_D3D12_ReleaseFeature"));auto destroy=reinterpret_cast<decltype(&NVSDK_NGX_D3D12_DestroyParameters)>(GetProcAddress(ngx,"NVSDK_NGX_D3D12_DestroyParameters"));
    std::ofstream result(report/L"quality-test.json");result<<"{\"cases\":[";bool first=true;
    for(int mode:{-1,2,0,3,100,101,102}){
        if(!select(mode))throw std::runtime_error("Quality selection failed");NVSDK_NGX_Parameter* p=nullptr;if(NVSDK_NGX_FAILED(caps(&p))||!p)throw std::runtime_error("Caps failed");void* pointer=nullptr;p->Get(NVSDK_NGX_Parameter_DLSSOptimalSettingsCallback,&pointer);if(!pointer)throw std::runtime_error("Optimal callback missing");
        p->Set(NVSDK_NGX_Parameter_Width,960u);p->Set(NVSDK_NGX_Parameter_Height,540u);p->Set(NVSDK_NGX_Parameter_PerfQualityValue,1);p->Set(NVSDK_NGX_Parameter_RTXValue,0);auto optimal=reinterpret_cast<PFN_NVSDK_NGX_DLSS_GetOptimalSettingsCallback>(pointer)(p);
        unsigned iw=0,ih=0;p->Get(NVSDK_NGX_Parameter_OutWidth,&iw);p->Get(NVSDK_NGX_Parameter_OutHeight,&ih);if(NVSDK_NGX_FAILED(optimal)||!iw||!ih)throw std::runtime_error("Optimal dimensions failed");
        p->Set(NVSDK_NGX_Parameter_PerfQualityValue,mode<0?1:cw_resolution::quality(mode));p->Set(NVSDK_NGX_Parameter_CreationNodeMask,1u);p->Set(NVSDK_NGX_Parameter_VisibilityNodeMask,1u);p->Set(NVSDK_NGX_Parameter_Width,iw);p->Set(NVSDK_NGX_Parameter_Height,ih);p->Set(NVSDK_NGX_Parameter_OutWidth,960u);p->Set(NVSDK_NGX_Parameter_OutHeight,540u);p->Set(NVSDK_NGX_Parameter_DLSS_Feature_Create_Flags,int(NVSDK_NGX_DLSS_Feature_Flags_IsHDR|NVSDK_NGX_DLSS_Feature_Flags_MVLowRes));p->Set(NVSDK_NGX_Parameter_DLSS_Enable_Output_Subrects,0);
        NVSDK_NGX_Handle* feature=nullptr;auto created=create(g.list.Get(),NVSDK_NGX_Feature_SuperSampling,p,&feature);if(NVSDK_NGX_FAILED(created)||!feature)throw std::runtime_error("SR create failed");
        auto color=texture(g.device.Get(),iw,ih,DXGI_FORMAT_R32G32B32A32_FLOAT),depth=texture(g.device.Get(),iw,ih,DXGI_FORMAT_R32_FLOAT),motion=texture(g.device.Get(),iw,ih,DXGI_FORMAT_R32G32_FLOAT),output=texture(g.device.Get(),960,540,DXGI_FORMAT_R32G32B32A32_FLOAT,true);
        std::vector<float> colours(size_t(iw)*ih*4,1.f),depths(size_t(iw)*ih,.5f),motions(size_t(iw)*ih*2,0.f);std::vector<ComPtr<ID3D12Resource>> uploads;uploads.push_back(upload(g,color.Get(),colours,4));uploads.push_back(upload(g,depth.Get(),depths,1));uploads.push_back(upload(g,motion.Get(),motions,2));
        p->Set(NVSDK_NGX_Parameter_Color,color.Get());p->Set(NVSDK_NGX_Parameter_Output,output.Get());p->Set(NVSDK_NGX_Parameter_Depth,depth.Get());p->Set(NVSDK_NGX_Parameter_MotionVectors,motion.Get());p->Set(NVSDK_NGX_Parameter_Jitter_Offset_X,0.f);p->Set(NVSDK_NGX_Parameter_Jitter_Offset_Y,0.f);p->Set(NVSDK_NGX_Parameter_MV_Scale_X,1.f);p->Set(NVSDK_NGX_Parameter_MV_Scale_Y,1.f);p->Set(NVSDK_NGX_Parameter_Reset,1);p->Set(NVSDK_NGX_Parameter_DLSS_Render_Subrect_Dimensions_Width,iw);p->Set(NVSDK_NGX_Parameter_DLSS_Render_Subrect_Dimensions_Height,ih);p->Set(NVSDK_NGX_Parameter_DLSS_Pre_Exposure,1.f);p->Set(NVSDK_NGX_Parameter_DLSS_Exposure_Scale,1.f);p->Set(NVSDK_NGX_Parameter_FrameTimeDeltaInMsec,16.667f);
        auto evaluated=evaluate(g.list.Get(),feature,p,nullptr);if(NVSDK_NGX_FAILED(evaluated))throw std::runtime_error("SR evaluate failed");g.submit();if(NVSDK_NGX_FAILED(release(feature)))throw std::runtime_error("SR release failed");destroy(p);
        if(!first)result<<',';first=false;result<<"{\"mode\":"<<mode<<",\"render\":["<<iw<<','<<ih<<"],\"optimal\":"<<unsigned(optimal)<<",\"create\":"<<unsigned(created)<<",\"evaluate\":"<<unsigned(evaluated)<<",\"fence_completed\":true}";
    }
    ComPtr<ID3D12InfoQueue> info;unsigned errors=0;if(SUCCEEDED(g.device.As(&info)))for(UINT64 i=0;i<info->GetNumStoredMessages();i++){SIZE_T bytes=0;info->GetMessage(i,nullptr,&bytes);std::vector<char> b(bytes);auto msg=reinterpret_cast<D3D12_MESSAGE*>(b.data());info->GetMessage(i,msg,&bytes);if(msg->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){errors++;std::cerr<<msg->pDescription<<'\n';}}
    result<<"],\"debug_errors\":"<<errors<<",\"status\":\""<<(errors?"failed":"passed")<<"\"}";if(errors)throw std::runtime_error("D3D12 validation failed");std::cout<<"All seven resolution modes passed creation, evaluation and GPU completion.\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
